# e) Power & Energy

Calculates power and energy output from the power station for daily river flow data depending on parameters given in a model file.

## Procedure

For each time step (day) in the input river flow data:
1. Determine the required Environmental Flows for each channel
2. Calculate resulting Generation, Canal Flow (and any spill flow)
3. Assign Canal Flow to turbines
4. Calculate headpond and tailwater elevations
5. Calculate headlosses and net head
6. Determine turbine and generator efficiency
7. Calculate power

## Inputs

| Data                       | Source                                        | Description                                 |
|----------------------------|-----------------------------------------------|---------------------------------------------|
| models.csv                  | | List of models with model paramters identified by Model Name  |
| ngonye_flow_daily_ewrx.csv        | Notebook: d_ewr_setup | Daily flow data annotated with Environmental Flow exceedance values |



## Outputs
| File                       | Description                                 |
|----------------------------|---------------------------------------------|
| [Model Name]_pe_daily.csv  | Daily power output  |
| [Model Name]_potential_generation_fdc.csv | Potential generation during testing and commissioning  |

## Libraries and Setup

In [1031]:
import numpy as np
import pandas as pd
from scipy import interpolate
import math

## Parameters

In [1032]:
year = ""  #Blank for 2017

In [1033]:
#Papermill parameters

#input_file='CC/ngonye_daily_WC2_56' #'ngonye_daily'#'CC/ngonye_daily_WC1_1'

input_file='ngonye_daily'

In [1034]:
input_data='./input_data/'
output_data='./output_data/'

if year != '':
    output_data += year + '/'
input_data, output_data

('./input_data/', './output_data/')

Set the model name below. This is used to lookup model parameters from the models list file.

- Base Case: Base Case
- MW162: Capacity reduced to 162MW
- Headpond50cm: Headpond level increased by 50cm
- EWRAllCs: All river reaches at a C rather than B environmental assurance level
- Extend Head: Minimum head reduce from 10m to 9m
- Tailwater Rise 50cm: Tailwater curve raised by 50cm
- Tailwater Fall 50cm: Tailwater curve dropped by 50cm

In [1035]:
model_name='Base Case Tender'
dryrun=False #Dont write output files

Read parameters for model

In [1036]:
if year != '':
    model_file=input_data + year + "/models.csv"
else:
    model_file=input_data + "models.csv"

models=pd.read_csv(model_file).set_index('ModelName')

model=models.loc[model_name]

out_prefix=model['OutputPrefix'] #'base'
if out_prefix!='base':
    out_prefix="scenarios/" + out_prefix

category_set_name=model['EWRCatSet']#'Recommendation 1'
headpond_lift=model['HeadpondLift']#0
tailwater_lift=model['TailwaterLift']#0

plant_capacity=model['Capacity'] #Base 180MW nominal capacity
# units=4 #Design no of units
units_avialable=model['UnitsAvailable'] #Available no of units

max_flow_unit=model['MaximumFlowUnit'] #275
rated_flow_unit=model['RatedFlowUnit'] #250
canal_capacity=max_flow_unit*4 #canal capacity 1100 cumec 
min_flow_unit=model['MinimumFlowUnit'] #50cumec minimum flow for a turbine

head_minimum=model['MinimumHead'] #minimum head 10m
head_maximum=model['MaximumHead'] #maximum head 25.4m
max_head_shutdown=model['MaxHeadShutdown'] 
rated_turbine_capacity=model['RatedTurbineCapacity'] #49.1MW
max_generator_output=model['MaxGeneratorOutput'] #48.2MW

optimise_turbines = model['OptimiseTurbines']

use_sino_hillchart = model['SinoHillchart']
use_sino_headlosses = model['SinoHeadlosses']


model_file, model

('./input_data/models.csv',
 OutputPrefix                                               base_tender
 Description             Base Case as provided to EPC Tender candidates
 EWRCatSet                                             Recommendation 1
 TailwaterLift                                                      0.0
 HeadpondLift                                                       0.0
 Capacity                                                           180
 MinimumHead                                                       10.0
 MaximumHead                                                       25.4
 MaxHeadShutdown                                                    0.0
 MinimumFlowUnit                                                   50.0
 MaximumFlowUnit                                                  275.0
 UnitsAvailable                                                       4
 RatedFlowUnit                                                    210.0
 RatedTurbineCapacity                                              49.1
 MaxGeneratorOutput                                                48.2
 OptimiseTurbines                                                     1
 SinoHillchart                                                        0
 SinoHeadlosses                                                       0
 Mean                                                       826764.8428
 P95                                                        712991.1548
 P90                                                        747145.8226
 P75                                                        789699.4536
 P50                                                        831504.4547
 P25                                                        868227.9715
 P10                                                         917740.791
 P5                                                         953598.0438
 StDev                                                      81747.80814
 CoefVar                                                       0.098877
 Max                                                        1013753.886
 Min                                                        489219.5772
 CapFactor                                                     0.524331
 CalYearMean                                                826822.4535
 CalYearStDev                                               77688.65864
 CalYearCoefVar                                                0.093961
 AutoCorrel                                                         NaN
 Power_max                                                        192.8
 CapFactor_Power_max                                           0.489555
 Power_Turbine1_max                                           49.851003
 P95FirmPower                                                 25.944707
 P90FirmPower                                                 29.806787
 Name: Base Case Tender, dtype: object)

## Load Daily Data

Load the daily flow time series which includes the exceedance values used for calculating daily EWRs.

In [1037]:
daily=pd.read_csv(output_data + input_file + '.csv')
daily=daily.set_index(pd.to_datetime(daily['Date'],format="%Y-%m-%d"))
daily=daily.drop('Date',axis=1)
if 'WaterWeek' in daily.columns:
    daily=daily.astype({'WaterWeek': 'int32'})
daily.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 33968 entries, 1924-10-01 to 2017-09-30
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   LaggedDate           33968 non-null  object
 1   VicFalls             33968 non-null  float64
 2   Conversion           33968 non-null  float64
 3   Flow                 33968 non-null  float64
 4   Exceedance           33968 non-null  float64
 5   Year                 33968 non-null  int64
 6   Month                33968 non-null  int64
 7   Day                  33968 non-null  int64
 8   MonthId              33968 non-null  float64
 9   WaterYear            33968 non-null  int64
 10  WaterMonth           33968 non-null  int64
 11  WaterDay             33968 non-null  int64
 12  WaterWeek            33968 non-null  int32
 13  Volume               33968 non-null  float64
 14  Flow_difference      33968 non-null  float64
 15  Flow_difference_pct  33968 non-null  float64
 16  EWRRefExceedance     33968 non-null  float64
dtypes: float64(9), int32(1), int64(6), object(1)
memory usage: 4.5+ MB

## EWR Assurance Category Set
Load the available EWR assurance category sets and select one

In [1038]:
category_sets=pd.read_csv(input_data + "ewr_section_categories.csv")
category_sets

  Section Recommendation 1 All Cs All Bs All As
0       A                B      C      B      A
1       C                B      C      B      A
2       D                B      C      B      A
3       E                B      C      B      A
4      FG                C      C      B      A

In [1039]:
category_set=category_sets.loc[:,['Section',category_set_name]]
category_set=category_set.rename(columns={category_set_name:'Category'})
category_set

  Section Category
0       A        B
1       C        B
2       D        B
3       E        B
4      FG        C

Load the EWR Flow Sets which specify the required EWRs by assurance category, flow and calendar month for each channel section

In [1040]:
ewr_flow_sets=pd.read_csv(input_data + "ewr_flow_sets.csv")
ewr_flow_sets=ewr_flow_sets.set_index(['Section','Category'])

## EWR Flow Sets
Select the EWR Flow Set for each channel section according to the Category Set chosen above (eg *Recommendation 1*)

In [1041]:
ewrs=category_set.join(ewr_flow_sets,on=['Section','Category']).set_index(['Section'])
ewrs_A=pd.melt(ewrs.loc['A'],id_vars=['Month'], value_vars=['Wet','Mod_Wet','Normal','Mod_Dry','Dry']).set_index(['Month','variable'])
ewrs_C=pd.melt(ewrs.loc['C'],id_vars=['Month'], value_vars=['Wet','Mod_Wet','Normal','Mod_Dry','Dry']).set_index(['Month','variable'])
ewrs_D=pd.melt(ewrs.loc['D'],id_vars=['Month'], value_vars=['Wet','Mod_Wet','Normal','Mod_Dry','Dry']).set_index(['Month','variable'])
ewrs_E=pd.melt(ewrs.loc['E'],id_vars=['Month'], value_vars=['Wet','Mod_Wet','Normal','Mod_Dry','Dry']).set_index(['Month','variable'])
ewrs_FG=pd.melt(ewrs.loc['FG'],id_vars=['Month'], value_vars=['Wet','Mod_Wet','Normal','Mod_Dry','Dry']).set_index(['Month','variable'])

## EWR Flow Bands
Annotate the daily flow series with the EWR Flow Band (Wet, Very Wet, Dry etc) - a lookup against the EWR Exceedance

In [1042]:
def flowBandNo(exceed):
    if exceed < 0.099:
        return 1
    elif  exceed < 0.399:
        return 2
    elif  exceed < 0.699:
        return 3
    elif  exceed < 0.899:
        return 4
    else:
        return 5
    
def flowBandLabel(bandNo):
    if bandNo == 1:
        return 'Wet'
    elif  bandNo == 2:
        return 'Mod_Wet'
    elif  bandNo == 3:
        return 'Normal'
    elif  bandNo ==4:
        return 'Mod_Dry'
    else:
        return 'Dry'    
    
def ewrLookup(section, band, month):
    return ewrs.loc[(section,month)][band]

Lookup the required EWR band based on daily exceedance

In [ ]:

daily['EWRBandNo']=daily.apply(lambda x: flowBandNo(x['EWRRefExceedance']),axis=1)
daily['EWRBandLabel']=daily.apply(lambda x: flowBandLabel(x['EWRBandNo']),axis=1) 
#daily[['Flow','EWRBandNo','EWRBandLabel']]

## EWR Flows
Lookup EWR flows

In [ ]:
def ewrMonthLookup(frame, month, category):
    return frame.loc[(month,category)].value

In [ ]:
#Calculate the required EWRs per channel
daily['EWRChannelA']=daily.apply(lambda x: ewrMonthLookup(ewrs_A,x['Month'],x['EWRBandLabel']),axis=1)
daily['EWRChannelC']=daily.apply(lambda x: ewrMonthLookup(ewrs_C,x['Month'],x['EWRBandLabel']),axis=1)
daily['EWRChannelD']=daily.apply(lambda x: ewrMonthLookup(ewrs_D,x['Month'],x['EWRBandLabel']),axis=1)
daily['EWRChannelE']=daily.apply(lambda x: ewrMonthLookup(ewrs_E,x['Month'],x['EWRBandLabel']),axis=1)
daily['EWRChannelFG']=daily.apply(lambda x: ewrMonthLookup(ewrs_FG,x['Month'],x['EWRBandLabel']),axis=1)
daily[['EWRChannelA','EWRChannelC','EWRChannelD','EWRChannelE','EWRChannelFG']]

            EWRChannelA  EWRChannelC  EWRChannelD  EWRChannelE  EWRChannelFG
Date
1924-10-01           37            5            3            2            50
1924-10-02           37            5            3            2            50
1924-10-03           37            5            3            2            50
1924-10-04           37            5            3            2            50
1924-10-05           37            5            3            2            50
...                 ...          ...          ...          ...           ...
2017-09-26           34            6            4            3            44
2017-09-27           34            6            4            3            44
2017-09-28           34            6            4            3            44
2017-09-29           34            6            4            3            44
2017-09-30           34            6            4            3            44

[33968 rows x 5 columns]

In [ ]:
#Sum of required EWRs per channel
daily['EWRTotal']=daily['EWRChannelA']+daily['EWRChannelC']+daily['EWRChannelD']+daily['EWRChannelE']+daily['EWRChannelFG']
daily['EWRProportion']=daily['EWRTotal']/daily['Flow']
#If required EWR is greater than total flow then reduce to total flow
daily['EWRTotal']=np.where(daily['EWRTotal']>daily['Flow'],daily['Flow'],daily['EWRTotal'])
daily[['Flow','EWRTotal','EWRProportion','EWRTotal']]

                  Flow  EWRTotal  EWRProportion  EWRTotal
Date
1924-10-01  111.407480      97.0       0.870678      97.0
1924-10-02  111.407480      97.0       0.870678      97.0
1924-10-03  111.407480      97.0       0.870678      97.0
1924-10-04  111.407480      97.0       0.870678      97.0
1924-10-05  111.407480      97.0       0.870678      97.0
...                ...       ...            ...       ...
2017-09-26  200.552607      91.0       0.453746      91.0
2017-09-27  200.552607      91.0       0.453746      91.0
2017-09-28  200.552607      91.0       0.453746      91.0
2017-09-29  200.552607      91.0       0.453746      91.0
2017-09-30  200.013130      91.0       0.454970      91.0

[33968 rows x 4 columns]

## Canal Flow and Turbine Flow

In [ ]:
#Available flow is total flow less EWR flow limited to canal capacity
daily['FlowAvailableForGeneration']=daily['Flow']-daily['EWRTotal']
daily[['Flow','FlowAvailableForGeneration']]

                  Flow  FlowAvailableForGeneration
Date
1924-10-01  111.407480                   14.407480
1924-10-02  111.407480                   14.407480
1924-10-03  111.407480                   14.407480
1924-10-04  111.407480                   14.407480
1924-10-05  111.407480                   14.407480
...                ...                         ...
2017-09-26  200.552607                  109.552607
2017-09-27  200.552607                  109.552607
2017-09-28  200.552607                  109.552607
2017-09-29  200.552607                  109.552607
2017-09-30  200.013130                  109.013130

[33968 rows x 2 columns]

In [ ]:
#Canal flow
daily['FlowCanal']=daily.apply(lambda x: min(x['FlowAvailableForGeneration'],units_avialable*max_flow_unit),axis=1)
daily.loc[daily['FlowCanal']<=min_flow_unit,'FlowCanal']=0
daily.loc[daily['FlowCanal']<=min_flow_unit,'LowFlowShutoff']=1
daily[['Flow','FlowCanal','LowFlowShutoff']]

                  Flow   FlowCanal  LowFlowShutoff
Date
1924-10-01  111.407480    0.000000             1.0
1924-10-02  111.407480    0.000000             1.0
1924-10-03  111.407480    0.000000             1.0
1924-10-04  111.407480    0.000000             1.0
1924-10-05  111.407480    0.000000             1.0
...                ...         ...             ...
2017-09-26  200.552607  109.552607             NaN
2017-09-27  200.552607  109.552607             NaN
2017-09-28  200.552607  109.552607             NaN
2017-09-29  200.552607  109.552607             NaN
2017-09-30  200.013130  109.013130             NaN

[33968 rows x 3 columns]

In [ ]:
def turbines(day):
    if optimise_turbines == 1:
        if day['FlowCanal'] <= rated_flow_unit*units_avialable:
            return math.ceil(day['FlowCanal']/rated_flow_unit)
        else:
            return units_avialable
    else:
        return math.ceil(day['FlowCanal'] / max_flow_unit)

In [ ]:
#Calculate number of turbines that will operate

daily['Turbines']=daily.apply(lambda x: turbines(x),axis=1)
daily[['Flow','FlowCanal','Turbines']]

                  Flow   FlowCanal  Turbines
Date
1924-10-01  111.407480    0.000000         0
1924-10-02  111.407480    0.000000         0
1924-10-03  111.407480    0.000000         0
1924-10-04  111.407480    0.000000         0
1924-10-05  111.407480    0.000000         0
...                ...         ...       ...
2017-09-26  200.552607  109.552607         1
2017-09-27  200.552607  109.552607         1
2017-09-28  200.552607  109.552607         1
2017-09-29  200.552607  109.552607         1
2017-09-30  200.013130  109.013130         1

[33968 rows x 3 columns]

In [ ]:
daily['FlowTurbine1']=np.where(daily['Turbines']>=1,daily['FlowCanal']/daily['Turbines'],0)
daily['FlowTurbine2']=np.where(daily['Turbines']>=2,daily['FlowCanal']/daily['Turbines'],0)
daily['FlowTurbine3']=np.where(daily['Turbines']>=3,daily['FlowCanal']/daily['Turbines'],0)
daily['FlowTurbine4']=np.where(daily['Turbines']==4,daily['FlowCanal']/daily['Turbines'],0)

In [ ]:
daily[['Flow','FlowCanal','Turbines','FlowTurbine1','FlowTurbine2','FlowTurbine3','FlowTurbine4']]

,Flow,FlowCanal,Turbines,FlowTurbine1,FlowTurbine2,FlowTurbine3,FlowTurbine4
Date,,,,,,,
1924-10-01,111.407480,0.000000,0,0.000000,0.0,0.0,0.0
1924-10-02,111.407480,0.000000,0,0.000000,0.0,0.0,0.0
1924-10-03,111.407480,0.000000,0,0.000000,0.0,0.0,0.0
1924-10-04,111.407480,0.000000,0,0.000000,0.0,0.0,0.0
1924-10-05,111.407480,0.000000,0,0.000000,0.0,0.0,0.0
...,...,...,...,...,...,...,...
2017-09-26,200.552607,109.552607,1,109.552607,0.0,0.0,0.0
2017-09-27,200.552607,109.552607,1,109.552607,0.0,0.0,0.0
2017-09-28,200.552607,109.552607,1,109.552607,0.0,0.0,0.0
2017-09-29,200.552607,109.552607,1,109.552607,0.0,0.0,0.0
2017-09-30,200.013130,109.013130,1,109.013130,0.0,0.0,0.0

## Spill and channel flows

In [ ]:
#Spill flows are any excess of the required EWR and generation flows
daily['FlowSpill']=daily['Flow']-daily['EWRTotal']-daily['FlowCanal']

#Apportion spill flows in same ratios as EWRs
daily['SpillChannelA']=daily['FlowSpill']*(daily['EWRChannelA']/daily['EWRTotal'])
daily['SpillChannelC']=daily['FlowSpill']*(daily['EWRChannelC']/daily['EWRTotal'])
daily['SpillChannelD']=daily['FlowSpill']*(daily['EWRChannelD']/daily['EWRTotal'])
daily['SpillChannelE']=daily['FlowSpill']*(daily['EWRChannelE']/daily['EWRTotal'])
daily['SpillChannelFG']=daily['FlowSpill']*(daily['EWRChannelFG']/daily['EWRTotal'])
daily[['FlowSpill','SpillChannelA','SpillChannelC','SpillChannelD','SpillChannelE','SpillChannelFG']]

,FlowSpill,SpillChannelA,SpillChannelC,SpillChannelD,SpillChannelE,SpillChannelFG
Date,,,,,,
1924-10-01,14.40748,5.495637,0.742654,0.445592,0.297061,7.426536
1924-10-02,14.40748,5.495637,0.742654,0.445592,0.297061,7.426536
1924-10-03,14.40748,5.495637,0.742654,0.445592,0.297061,7.426536
1924-10-04,14.40748,5.495637,0.742654,0.445592,0.297061,7.426536
1924-10-05,14.40748,5.495637,0.742654,0.445592,0.297061,7.426536
...,...,...,...,...,...,...
2017-09-26,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
2017-09-27,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
2017-09-28,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
2017-09-29,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
2017-09-30,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000

In [ ]:
#Other flows
daily['FlowChannelA']=daily['SpillChannelA']+daily['EWRChannelA']
daily['FlowChannelC']=daily['SpillChannelC']+daily['EWRChannelC']
daily['FlowChannelD']=daily['SpillChannelD']+daily['EWRChannelD']
daily['FlowChannelE']=daily['SpillChannelE']+daily['EWRChannelE']

daily['TmpA']=np.where(daily['FlowChannelA']>100,daily['FlowChannelA']-100,0)
daily['SpillChannelA']=daily['SpillChannelA']-daily['TmpA']
daily['FlowChannelA']=daily['FlowChannelA']-daily['TmpA']
daily['SpillChannelFG']=daily['SpillChannelFG']+daily['TmpA']

daily['TmpC']=np.where(daily['FlowChannelC']>18,daily['FlowChannelC']-18,0)
daily['SpillChannelC']=daily['SpillChannelC']-daily['TmpC']
daily['FlowChannelC']=daily['FlowChannelC']-daily['TmpC']
daily['SpillChannelFG']=daily['SpillChannelFG']+daily['TmpC']

daily['TmpD']=np.where(daily['FlowChannelD']>25,daily['FlowChannelD']-25,0)
daily['SpillChannelD']=daily['SpillChannelD']-daily['TmpD']
daily['FlowChannelD']=daily['FlowChannelD']-daily['TmpD']
daily['SpillChannelFG']=daily['SpillChannelFG']+daily['TmpD']

daily['TmpE']=np.where(daily['FlowChannelE']>80,daily['FlowChannelE']-80,0)
daily['SpillChannelE']=daily['SpillChannelE']-daily['TmpE']
daily['FlowChannelE']=daily['FlowChannelE']-daily['TmpE']
daily['SpillChannelFG']=daily['SpillChannelFG']+daily['TmpE']

daily['FlowChannelFG']=daily['SpillChannelFG']+daily['EWRChannelFG']
daily=daily.drop(['TmpA','TmpC','TmpD','TmpE'],axis=1)

daily['FlowLeftChannel']=daily['FlowChannelA']+daily['FlowChannelC']+daily['FlowChannelD']+daily['FlowCanal']

## Levels, headloss and head

Headpond level

In [ ]:
def headpondLevel(flow):
    if flow<5000:
        return 990.0 + headpond_lift
    elif flow<7500:
        return 0.000081307*flow+989.6 + headpond_lift
    else:
        return 0.000240*flow+988.4 + headpond_lift

In [ ]:
daily['LevelHeadpond']=daily['Flow'].apply(headpondLevel)

Tailwater Level

In [ ]:
tailwater_levels=pd.read_csv(input_data + "tailwater_levels.csv")

In [ ]:
def tailwaterLevel(flow):
    return np.interp(flow,tailwater_levels['flow'],tailwater_levels['level']) + tailwater_lift

    #OLD
    #return ((1.0267*10**-11)*flow**3) + ((-3.3603*10**-7)*flow**2) + ((4.2508*10**-3)*flow) + 963.86

    #OLD
    #log_flow=math.log10(flow)
    #if log_flow>=3.8:
    #    return -21.429*log_flow**2+182.03*log_flow+597.15
    #elif log_flow>=2.3:
    #    return 6.5299*log_flow**2-30.155*log_flow+999.52
    #else:
    #    return -2.6828*log_flow**2+11.265*log_flow+952.68'

In [ ]:
daily['LevelTailwater']=daily['Flow'].apply(tailwaterLevel)
daily['HeadGross']=daily['LevelHeadpond']-daily['LevelTailwater']

Left channel headloss

In [ ]:
headloss_leftchannel=pd.read_csv(input_data + "headloss_leftchannel.csv")

In [ ]:
# Extract the flow and headloss values from the dataframe
levels = headloss_leftchannel['Level'].values
flows = headloss_leftchannel.columns[1:].astype(float).values
headloss_values = headloss_leftchannel.drop('Level', axis=1).values

# Create the 2D interpolation function
fHeadlossLeftChannel2D = interpolate.RegularGridInterpolator((levels, flows), headloss_values)

# Add a column to the daily dataframe with the headloss for the flow in the left channel
daily['HeadlossLeftChannel'] = fHeadlossLeftChannel2D(np.column_stack((daily['LevelHeadpond']-headpond_lift, daily['FlowLeftChannel'])))
#daily[['Flow','HeadlossLeftChannel']]

Canal headloss

In [ ]:
headloss_canal=pd.read_csv(input_data + 'headloss_canal_sh.csv' if use_sino_headlosses else input_data + 'headloss_canal_fs.csv')
#headloss_canal

In [ ]:

fHeadlossCanal = interpolate.interp1d(headloss_canal['FlowCanal'], headloss_canal['HeadlossCanal'], fill_value="extrapolate")

daily['HeadlossCanal']=daily['FlowCanal'].apply(fHeadlossCanal)
daily['LevelForebay']=daily['LevelHeadpond']-daily['HeadlossLeftChannel']-daily['HeadlossCanal']

In [ ]:
#daily[['FlowCanal','HeadlossLeftChannel','HeadlossCanal','LevelHeadpond','LevelForebay']]

In [ ]:
headloss_turbine=pd.read_csv(input_data + 'headloss_turbine_sh.csv' if use_sino_headlosses else input_data + 'headloss_turbine_fs.csv')
#headloss_turbine

In [ ]:
fHeadlossTurbine = interpolate.interp1d(headloss_turbine['FlowCanal'], headloss_turbine['HeadlossTurbine'], fill_value="extrapolate")

daily['HeadlossTurbine1']=daily['FlowTurbine1'].apply(fHeadlossTurbine)
daily['HeadlossTurbine2']=daily['FlowTurbine2'].apply(fHeadlossTurbine)
daily['HeadlossTurbine3']=daily['FlowTurbine3'].apply(fHeadlossTurbine)
daily['HeadlossTurbine4']=daily['FlowTurbine4'].apply(fHeadlossTurbine)

#daily[['Flow','HeadlossTurbine1','HeadlossTurbine2' ,'HeadlossTurbine3','HeadlossTurbine4']]

In [ ]:
daily['HeadTurbine1']=daily['LevelForebay']-daily['LevelTailwater']-daily['HeadlossTurbine1']
daily['HeadTurbine2']=daily['LevelForebay']-daily['LevelTailwater']-daily['HeadlossTurbine2']
daily['HeadTurbine3']=daily['LevelForebay']-daily['LevelTailwater']-daily['HeadlossTurbine3']
daily['HeadTurbine4']=daily['LevelForebay']-daily['LevelTailwater']-daily['HeadlossTurbine4']

In [ ]:
if max_head_shutdown == 0:
    daily['HeadTurbine1'] = np.where(daily['HeadTurbine1'] > head_maximum, head_maximum, daily['HeadTurbine1'])
    daily['HeadTurbine2'] = np.where(daily['HeadTurbine2'] > head_maximum, head_maximum, daily['HeadTurbine2'])
    daily['HeadTurbine3'] = np.where(daily['HeadTurbine3'] > head_maximum, head_maximum, daily['HeadTurbine3'])
    daily['HeadTurbine4'] = np.where(daily['HeadTurbine4'] > head_maximum, head_maximum, daily['HeadTurbine4'])

max_head_shutdown

np.float64(0.0)

In [ ]:
#Below minimum head then 0 generation. 0 flow in canal.
daily.loc[daily['HeadTurbine1']<=head_minimum,'SpillChannelA']=daily.loc[daily['HeadTurbine1']<=head_minimum,'SpillChannelA']+daily.loc[daily['HeadTurbine1']<=head_minimum,'FlowCanal']
daily.loc[daily['HeadTurbine1']<=head_minimum,'FlowChannelA']=daily.loc[daily['HeadTurbine1']<=head_minimum,'FlowChannelA']+daily.loc[daily['HeadTurbine1']<=head_minimum,'FlowCanal']
daily.loc[daily['HeadTurbine1']<=head_minimum,'FlowSpill']=daily.loc[daily['HeadTurbine1']<=head_minimum,'FlowSpill']+daily.loc[daily['HeadTurbine1']<=head_minimum,'FlowCanal']

daily.loc[daily['HeadTurbine1']<=head_minimum,'FlowCanal']=0
daily.loc[daily['HeadTurbine1']<=head_minimum,'Turbines']=0
daily.loc[daily['HeadTurbine1']<=head_minimum,'LowHeadShutoff']=1

## Efficiency, power and energy

In [ ]:
#daily[['FlowCanal','HeadTurbine1','HeadTurbine2','HeadTurbine3','HeadTurbine4']]

In [ ]:
hillchart=pd.read_csv(input_data + 'hillchart_sh.csv' if use_sino_hillchart else input_data + 'hillchart_fs.csv')
#hillchart

In [ ]:
# Extract the values from the dataframe
flows = hillchart['Flow'].values
heads = hillchart.columns[1:].astype(float).values
values = hillchart.drop('Flow', axis=1).values

# Create the 2D interpolation function
fTurbineEfficiency = interpolate.RegularGridInterpolator((flows, heads), values)

# Add a column to the daily dataframe with the headloss for the flow in the left channel
daily['EffTurbine1'] = fTurbineEfficiency(np.column_stack((daily['FlowTurbine1'], daily['HeadTurbine1'])))
daily['EffTurbine2'] = fTurbineEfficiency(np.column_stack((daily['FlowTurbine2'], daily['HeadTurbine2'])))
daily['EffTurbine3'] = fTurbineEfficiency(np.column_stack((daily['FlowTurbine3'], daily['HeadTurbine3'])))
daily['EffTurbine4'] = fTurbineEfficiency(np.column_stack((daily['FlowTurbine4'], daily['HeadTurbine4'])))

In [ ]:
if max_head_shutdown == 1:
    daily['EffTurbine1'] = np.where(daily['HeadTurbine1'] > head_maximum, 0, daily['EffTurbine1'])
    daily['EffTurbine2'] = np.where(daily['HeadTurbine2'] > head_maximum, 0, daily['EffTurbine2'])
    daily['EffTurbine3'] = np.where(daily['HeadTurbine3'] > head_maximum, 0, daily['EffTurbine3'])
    daily['EffTurbine4'] = np.where(daily['HeadTurbine4'] > head_maximum, 0, daily['EffTurbine4'])

daily['EffTurbine1'] = np.where(daily['LowHeadShutoff']==1,0,daily['EffTurbine1'])
daily['EffTurbine2'] = np.where(daily['LowHeadShutoff']==1,0,daily['EffTurbine2'])
daily['EffTurbine3'] = np.where(daily['LowHeadShutoff']==1,0,daily['EffTurbine3'])
daily['EffTurbine4'] = np.where(daily['LowHeadShutoff']==1,0,daily['EffTurbine4'])

In [ ]:
daily[['Flow','HeadTurbine1','FlowTurbine1','EffTurbine1']]

                  Flow  HeadTurbine1  FlowTurbine1  EffTurbine1
Date
1924-10-01  111.407480          25.4      0.000000     0.000000
1924-10-02  111.407480          25.4      0.000000     0.000000
1924-10-03  111.407480          25.4      0.000000     0.000000
1924-10-04  111.407480          25.4      0.000000     0.000000
1924-10-05  111.407480          25.4      0.000000     0.000000
...                ...           ...           ...          ...
2017-09-26  200.552607          25.4    109.552607     0.893642
2017-09-27  200.552607          25.4    109.552607     0.893642
2017-09-28  200.552607          25.4    109.552607     0.893642
2017-09-29  200.552607          25.4    109.552607     0.893642
2017-09-30  200.013130          25.4    109.013130     0.893190

[33968 rows x 4 columns]

In [ ]:
daily['PowerTurbine1']=daily['FlowTurbine1']*daily['HeadTurbine1']*daily['EffTurbine1']*9.81*999.7/1000000
daily['PowerTurbine2']=daily['FlowTurbine2']*daily['HeadTurbine2']*daily['EffTurbine2']*9.81*999.7/1000000
daily['PowerTurbine3']=daily['FlowTurbine3']*daily['HeadTurbine3']*daily['EffTurbine3']*9.81*999.7/1000000
daily['PowerTurbine4']=daily['FlowTurbine4']*daily['HeadTurbine4']*daily['EffTurbine4']*9.81*999.7/1000000

In [ ]:
daily['LoadFactorTurbine1']=daily['PowerTurbine1']/rated_turbine_capacity
daily['LoadFactorTurbine2']=daily['PowerTurbine2']/rated_turbine_capacity
daily['LoadFactorTurbine3']=daily['PowerTurbine3']/rated_turbine_capacity
daily['LoadFactorTurbine4']=daily['PowerTurbine4']/rated_turbine_capacity

In [ ]:
generator_efficiency=pd.read_csv(input_data + 'generator_efficiency.csv')

In [ ]:
fGeneratorEfficiency = interpolate.interp1d(generator_efficiency['TurbinePowerFactor'], generator_efficiency['Efficiency'], fill_value="extrapolate")

daily['EffGen1']=daily['LoadFactorTurbine1'].apply(fGeneratorEfficiency)
daily['EffGen2']=daily['LoadFactorTurbine2'].apply(fGeneratorEfficiency)
daily['EffGen3']=daily['LoadFactorTurbine3'].apply(fGeneratorEfficiency)
daily['EffGen4']=daily['LoadFactorTurbine4'].apply(fGeneratorEfficiency)
# daily[['Flow' ,'EffGen1','EffGen2']]

In [ ]:

daily['PowerGenerator1']=daily['PowerTurbine1']*daily['EffGen1']
daily['PowerGenerator2']=daily['PowerTurbine2']*daily['EffGen2']
daily['PowerGenerator3']=daily['PowerTurbine3']*daily['EffGen3']
daily['PowerGenerator4']=daily['PowerTurbine4']*daily['EffGen4']


daily['PowerGenerator1'] = np.where(daily['PowerGenerator1'] > max_generator_output, max_generator_output, daily['PowerGenerator1'])
daily['PowerGenerator2'] = np.where(daily['PowerGenerator2'] > max_generator_output, max_generator_output, daily['PowerGenerator2'])
daily['PowerGenerator3'] = np.where(daily['PowerGenerator3'] > max_generator_output, max_generator_output, daily['PowerGenerator3'])
daily['PowerGenerator4'] = np.where(daily['PowerGenerator4'] > max_generator_output, max_generator_output, daily['PowerGenerator4'])

In [ ]:

daily['Power']=np.nan_to_num(daily['PowerGenerator1'])+np.nan_to_num(daily['PowerGenerator2'])+np.nan_to_num(daily['PowerGenerator3'])+np.nan_to_num(daily['PowerGenerator4'])
daily['Energy']=daily['Power']*24
daily['PerfMwPerCumec']=daily['Power']/daily['Flow']
daily['PerfMWhPerm3']=daily['Energy']/(daily['FlowCanal']*60*60*24)

In [ ]:
daily.loc['2016-12-29'].name

Timestamp('2016-12-29 00:00:00')

In [ ]:
daily.loc['1968-9-17'][['Month','Day','Flow','EWRRefExceedance','EWRBandLabel','EWRChannelA','EWRChannelC','EWRChannelD','EWRChannelE','EWRChannelFG','EWRTotal','FlowLeftChannel','FlowCanal','Turbines','FlowTurbine1','FlowTurbine2','LevelHeadpond','LevelTailwater', 'HeadGross','HeadlossLeftChannel','HeadlossCanal','HeadlossTurbine1','HeadTurbine1','LoadFactorTurbine1','EffTurbine1','PowerTurbine1','EffGen1','PowerGenerator1','Power', 'Energy','PerfMwPerCumec','PerfMWhPerm3']]

Month                            9
Day                             17
Flow                    391.816912
EWRRefExceedance              0.08
EWRBandLabel                   Wet
EWRChannelA                     48
EWRChannelC                      8
EWRChannelD                      7
EWRChannelE                      4
EWRChannelFG                    79
EWRTotal                     146.0
FlowLeftChannel         308.816912
FlowCanal               245.816912
Turbines                         2
FlowTurbine1            122.908456
FlowTurbine2            122.908456
LevelHeadpond                990.0
LevelTailwater          965.359085
HeadGross                24.640915
HeadlossLeftChannel       0.144523
HeadlossCanal             0.019163
HeadlossTurbine1          0.106961
HeadTurbine1             24.370269
LoadFactorTurbine1        0.540547
EffTurbine1               0.903513
PowerTurbine1            26.540865
EffGen1                       0.97
PowerGenerator1          25.744639
Power                    51.489278
Energy                 1235.742681
PerfMwPerCumec            0.131412
PerfMWhPerm3              0.000058
Name: 1968-09-17 00:00:00, dtype: object

## Generation potential for testing and commissioning

In [ ]:
#Calculate 'potential generation' aginst the flow FDC.
#Potential generation assumes flow can be stored in the headpond and only head is limiting

# fdc=pd.read_csv("./output_data/ngonye_flow_fdc.csv").set_index('Exceedance')
# fdc['LevelTailwater']=fdc['Flow'].apply(tailwaterLevel)
# fdc['LevelHeadpond']=fdc['Flow'].apply(headpondLevel)

# fdc['1uFlowLeftChannel']=max_flow_unit+100
# fdc['1uHeadlossLeftChannel']=fdc['1uFlowLeftChannel'].apply(fHeadlossLeftChannel)
# fdc['2uFlowLeftChannel']=(max_flow_unit*2)+100
# fdc['2uHeadlossLeftChannel']=fdc['2uFlowLeftChannel'].apply(fHeadlossLeftChannel)
# fdc['3uFlowLeftChannel']=(max_flow_unit*3)+100
# fdc['3uHeadlossLeftChannel']=fdc['3uFlowLeftChannel'].apply(fHeadlossLeftChannel)
# fdc['4uFlowLeftChannel']=(max_flow_unit*4)+100
# fdc['4uHeadlossLeftChannel']=fdc['4uFlowLeftChannel'].apply(fHeadlossLeftChannel)

# u1headlossCanal=fHeadlossCanal(max_flow_unit)
# u2headlossCanal=fHeadlossCanal(max_flow_unit*2)
# u3headlossCanal=fHeadlossCanal(max_flow_unit*3)
# u4headlossCanal=fHeadlossCanal(max_flow_unit*4)

# fdc['1uLevelForebay']=fdc['LevelHeadpond']-fdc['1uHeadlossLeftChannel']-u1headlossCanal
# fdc['2uLevelForebay']=fdc['LevelHeadpond']-fdc['2uHeadlossLeftChannel']-u2headlossCanal
# fdc['3uLevelForebay']=fdc['LevelHeadpond']-fdc['3uHeadlossLeftChannel']-u3headlossCanal
# fdc['4uLevelForebay']=fdc['LevelHeadpond']-fdc['4uHeadlossLeftChannel']-u4headlossCanal

# headlossTurbine=turbineHeadloss(max_flow_unit)

# fdc['1uHead']=fdc['1uLevelForebay']-fdc['LevelTailwater']-headlossTurbine
# fdc['2uHead']=fdc['2uLevelForebay']-fdc['LevelTailwater']-headlossTurbine
# fdc['3uHead']=fdc['3uLevelForebay']-fdc['LevelTailwater']-headlossTurbine
# fdc['4uHead']=fdc['4uLevelForebay']-fdc['LevelTailwater']-headlossTurbine

# loadFactor=max_flow_unit/rated_flow_unit
# fdc['1uEffTurbine']=fdc.apply(lambda x: turbineEfficiency2(loadFactor,x['1uHead']),axis=1)
# fdc['2uEffTurbine']=fdc.apply(lambda x: turbineEfficiency2(loadFactor,x['2uHead']),axis=1)
# fdc['3uEffTurbine']=fdc.apply(lambda x: turbineEfficiency2(loadFactor,x['3uHead']),axis=1)
# fdc['4uEffTurbine']=fdc.apply(lambda x: turbineEfficiency2(loadFactor,x['4uHead']),axis=1)

# effGen=generatorEff(loadFactor)

# fdc['1uPowerPotential']=1*max_flow_unit*fdc['1uHead']*fdc['1uEffTurbine']*effGen*9.81/1000
# fdc['2uPowerPotential']=2*max_flow_unit*fdc['2uHead']*fdc['2uEffTurbine']*effGen*9.81/1000
# fdc['3uPowerPotential']=3*max_flow_unit*fdc['3uHead']*fdc['3uEffTurbine']*effGen*9.81/1000
# fdc['4uPowerPotential']=4*max_flow_unit*fdc['4uHead']*fdc['4uEffTurbine']*effGen*9.81/1000

# fdc

In [ ]:
# fPotential1u = interpolate.interp1d(fdc['Flow'], fdc['1uPowerPotential'], fill_value="extrapolate")
# fPotential2u = interpolate.interp1d(fdc['Flow'], fdc['2uPowerPotential'], fill_value="extrapolate")
# fPotential3u = interpolate.interp1d(fdc['Flow'], fdc['3uPowerPotential'], fill_value="extrapolate")
# fPotential4u = interpolate.interp1d(fdc['Flow'], fdc['4uPowerPotential'], fill_value="extrapolate")
# interpolate.interp2d()

In [ ]:
# daily['PotentialPower1u']=daily['Flow'].apply(fPotential1u)
# daily['PotentialPower2u']=daily['Flow'].apply(fPotential2u)
# daily['PotentialPower3u']=daily['Flow'].apply(fPotential3u)
# daily['PotentialPower4u']=daily['Flow'].apply(fPotential4u)

## Save

In [ ]:
daily

,LaggedDate,VicFalls,Conversion,Flow,Exceedance,Year,Month,Day,MonthId,WaterYear,...,EffGen3,EffGen4,PowerGenerator1,PowerGenerator2,PowerGenerator3,PowerGenerator4,Power,Energy,PerfMwPerCumec,PerfMWhPerm3
Date,,,,,,,,,,,,,,,,,,,,,
1924-10-01,1924-10-12,100.0000,1.114075,111.407480,0.999,1924,10,1,1924.10,1924,...,0.96,0.96,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN
1924-10-02,1924-10-13,100.0000,1.114075,111.407480,0.999,1924,10,2,1924.10,1924,...,0.96,0.96,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN
1924-10-03,1924-10-14,100.0000,1.114075,111.407480,0.999,1924,10,3,1924.10,1924,...,0.96,0.96,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN
1924-10-04,1924-10-15,100.0000,1.114075,111.407480,0.999,1924,10,4,1924.10,1924,...,0.96,0.96,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN
1924-10-05,1924-10-16,100.0000,1.114075,111.407480,0.999,1924,10,5,1924.10,1924,...,0.96,0.96,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-09-26,2017-10-07,204.0855,0.982689,200.552607,0.955,2017,9,26,2017.09,2016,...,0.96,0.96,23.647325,0.0,0.0,0.0,23.647325,567.535810,0.117911,0.00006
2017-09-27,2017-10-08,204.0855,0.982689,200.552607,0.955,2017,9,27,2017.09,2016,...,0.96,0.96,23.647325,0.0,0.0,0.0,23.647325,567.535810,0.117911,0.00006
2017-09-28,2017-10-09,204.0855,0.982689,200.552607,0.955,2017,9,28,2017.09,2016,...,0.96,0.96,23.647325,0.0,0.0,0.0,23.647325,567.535810,0.117911,0.00006
2017-09-29,2017-10-10,204.0855,0.982689,200.552607,0.955,2017,9,29,2017.09,2016,...,0.96,0.96,23.647325,0.0,0.0,0.0,23.647325,567.535810,0.117911,0.00006
2017-09-30,2017-10-11,200.9197,0.995488,200.013130,0.958,2017,9,30,2017.09,2016,...,0.96,0.96,23.512430,0.0,0.0,0.0,23.512430,564.298322,0.117554,0.00006

In [ ]:
output_data + out_prefix + '_pe_daily.csv'

'./output_data/scenarios/base_tender_pe_daily.csv'

In [ ]:
if dryrun==False:
    daily.to_csv(output_data + out_prefix + '_pe_daily.csv')
    #fdc.to_csv(output_data + out_prefix + '_potential_generation_fdc.csv')

In [ ]:
# OLD

# def generatorEff(load_fact):
#     if np.isnan(load_fact):
#         return np.nan
    
#     if load_fact==0:
#         return 0
#     elif load_fact<=0.45:
#         return 0.96
#     elif load_fact<=0.85:
#         return 0.97
#     else:
#         return 0.98'


# OLD
# def turbineEfficiency2(load_fact,h):
    
#     q=load_fact
    
#     if np.isnan(h) : return np.nan
    
#     if h<=head_minimum: return 0
    
#     if q==0: return 0
#     elif q<0.214: return 0.77
#     elif q<0.22: return 0.78
#     elif q<0.234: return 0.79
#     elif q<0.248: return 0.80
#     elif q<0.256: return 0.81
#     elif q<0.266: return 0.82
#     elif q<0.28: return 0.83
#     elif q<0.288: return 0.84
#     elif q<0.298: return 0.85
#     elif q<0.33: return 0.86
#     elif q<0.366: return 0.87
#     elif q<0.402: return 0.88
#     elif q<0.4388: return 0.89
#     elif q<0.48708: return 0.90
#     elif q<0.5872: return 0.91
#     elif q<0.6781: return 0.92
#     elif q<0.6924:
#         if h<24.65: return 0.92
#         else: return 0.93
#     elif q<0.7992: return 0.93
#     elif q<0.8448:
#         if h<23: return 0.93
#         else: return 0.94
#     elif q<0.9882:
#         return 0.94
#     elif q<1.0:
#         if h<24.16: return 0.94
#         else: return 0.95
#     elif q<1.04:
#         if h<23.6: return 0.94
#         else: return 0.95
#     elif q<1.1:
#         if h<22.5: return 0.94
#         else: return 0.95
#     else:
#         return -0.0015*h**2 + 0.0565*h + 0.4

# OLD
# def turbineEfficiency(q_actual,h):
    
#     #Scale flow to installed capacity
#     q=q_actual*(180/plant_capacity)
    
#     if np.isnan(h) or np.isnan(q): return np.nan
    
#     if h<=head_minimum: return 0
    
#     if q==0: return 0
#     elif q<53.5: return 0.77
#     elif q<55: return 0.78
#     elif q<58.5: return 0.79
#     elif q<62: return 0.80
#     elif q<64: return 0.81
#     elif q<66.5: return 0.82
#     elif q<70: return 0.83
#     elif q<72: return 0.84
#     elif q<74.5: return 0.85
#     elif q<82.5: return 0.86
#     elif q<91.5: return 0.87
#     elif q<100.5: return 0.88
#     elif q<109.72: return 0.89
#     elif q<121.77: return 0.90
#     elif q<146.8: return 0.91
#     elif q<169.545: return 0.92
#     elif q<173.1:
#         if h<24.65: return 0.92
#         else: return 0.93
#     elif q<199.8: return 0.93
#     elif q<211.2:
#         if h<23: return 0.93
#         else: return 0.94
#     elif q<247.05:
#         return 0.94
#     elif q<250:
#         if h<24.16: return 0.94
#         else: return 0.95
#     elif q<260:
#         if h<23.6: return 0.94
#         else: return 0.95
#     elif q<275:
#         if h<22.5: return 0.94
#         else: return 0.95
#     else:
#         return -0.0015*h**2 + 0.0565*h + 0.4

In [ ]:
# OLD

# def turbineHeadloss(flow):
#     if np.isnan(flow):
#         return np.nan
#     elif flow==0:
#         return 0
#     else:
#         #Feasibility version
#         return 0.00000702*flow**2+0.00002226*flow-0.00207422